In [1]:
from pyrootmemo.fit.fit_xy_powerlaw import PowerlawFitWeibull
from pyrootmemo.materials import MultipleRoots
import numpy as np
from pyrootmemo.tools.helpers import units

In [2]:
# generate data
rng = np.random.default_rng()
x = np.linspace(1, 5, 50)
y = 10 * x**(-0.5) * rng.uniform(0.5, 1.5, len(x))
w = np.ones(len(x))
# with units - generate
xu = x * units("mm")
yu = y * units("MPa")
# show
#print(x)
#print(y)

In [3]:
# Weibull
P = PowerlawFitWeibull(x, y)
print(P.colinear)
print(P.multiplier)
print(P.exponent)
print(P.shape)
print(P.random(np.array([2, 3, 4])))
print(P.ks_distance())
print(P.covariance())
print(P.covariance(method = 'bootstrap'))
#print(P.confidence_interval())

False
8.438924924108509
-0.42154047630779584
3.5879470189635696
[2.96620895 5.20885248 4.89188396]
0.8587224373807033
[[ 0.73999661 -0.07113584  0.05953369]
 [-0.07113584  0.00840657  0.00083034]
 [ 0.05953369  0.00083034  0.1617134 ]]
[[39 15 24 ... 21 18 42]
 [15  9 47 ...  0 25 36]
 [48 22 27 ... 32  3 23]
 ...
 [43 47 48 ... 26 42  7]
 [41 17 13 ...  1 46 14]
 [43 18 47 ... 14 13 48]]
[[ 9.27061508 -0.50868731  3.58055198]
 [ 9.09142801 -0.50275973  3.68068011]
 [ 9.10502878 -0.4273311   4.19841363]
 [ 8.97288019 -0.44579133  3.44324473]
 [ 8.87452982 -0.46470354  3.68773002]
 [ 8.19545611 -0.37424626  3.6066073 ]
 [ 7.82994148 -0.35793954  3.47954615]
 [ 9.30482507 -0.48005654  3.8412317 ]
 [ 8.44685619 -0.43416681  3.61665754]
 [ 8.31641352 -0.34805578  3.70921886]
 [10.06384098 -0.56609726  3.55357245]
 [ 7.37413592 -0.37982052  3.23811486]
 [ 7.60357996 -0.4166673   3.25139744]
 [ 7.50250488 -0.24140318  4.03831637]
 [ 9.48324147 -0.48920306  3.79698371]
 [ 7.76342914 -0.314288

In [ ]:
# Weibull with units
Pu = PowerlawFitWeibull(xu, yu)
print(Pu.x0)
print(Pu.y0)
print(Pu.colinear)
print(Pu.multiplier)
print(Pu.exponent)
print(Pu.shape)
print(Pu.random(np.array([2, 3, 4]) * units("mm")))
print(Pu.ks_distance())
#print(Pu.xrange())
#print(Pu.predict())
#print(Pu.get_scale(Pu.xrange()))
#print(Pu.prediction_interval(level = 0.5))
print(Pu.covariance())
print(Pu.covariance(method = 'bootstrap'))
#print(Pu.confidence_interval())


[1.2448979591836735 1.163265306122449 1.0816326530612246] millimeter
1.0 millimeter
1.0 megapascal
False
8.438924924108509 megapascal
-0.42154047630779584
3.5879470189635696
[5.209108376518797 1.8435929043187358 4.46380607801537] megapascal
0.8587224373807033 dimensionless
[[ 0.73999661 -0.07113584  0.05953369]
 [-0.07113584  0.00840657  0.00083034]
 [ 0.05953369  0.00083034  0.1617134 ]]
[[ 7 10 33 ... 34 11 44]
 [27 37 38 ... 46 29 28]
 [ 1 32  3 ... 22 27 30]
 ...
 [14 47 12 ... 30 38 15]
 [25 42 38 ...  6 25 13]
 [22 38 39 ... 49  0 39]]


ValueError: setting an array element with a sequence.