In [1]:
from pyrootmemo.pullout import Pullout_embedded_elastic, Pullout_embedded_elastic_slipping
from pyrootmemo.pullout import Pullout_embedded_elastic_breakage, Pullout_embedded_elastic_breakage_slipping
from pyrootmemo.pullout import Pullout_embedded_elastoplastic, Pullout_embedded_elastoplastic_slipping
from pyrootmemo.pullout import Pullout_embedded_elastoplastic_breakage, Pullout_embedded_elastoplastic_breakage_slipping
from pyrootmemo.materials import MultipleRoots, Interface
from pyrootmemo.tools.helpers import units
import numpy as np

In [2]:
# generate some root data
from collections import namedtuple
Parameter = namedtuple("parameter", "value unit")
roots = MultipleRoots(
    species = "test_species",
    diameter = Parameter([1, 6, 3], 'mm'),
    yield_strength = Parameter([15, 10, 5], 'MPa'),
    tensile_strength = Parameter([30, 20, 10], 'MPa'),
    elastic_modulus = Parameter([100, 20, 100], 'MPa'),
    plastic_modulus = Parameter([50, 10, 50], 'MPa'),
    length = Parameter([1, 1, 0.01], 'm')
)
# interface data
interface = Interface(shear_strength = Parameter(10, "kPa"))
# Weibull shape parameter
weibull_shape = 10 

In [6]:
#p = Pullout_base(roots, soil_resistance)
#print(p.roots.xsection)

p0 = Pullout_embedded_elastic(roots, interface)
p1 = Pullout_embedded_elastic_slipping(roots, interface)
p2 = Pullout_embedded_elastic_breakage(roots, interface)
p3 = Pullout_embedded_elastic_breakage_slipping(roots, interface)
p4 = Pullout_embedded_elastoplastic(roots, interface)
p5 = Pullout_embedded_elastoplastic_slipping(roots, interface)
p6 = Pullout_embedded_elastoplastic_breakage(roots, interface, weibull_shape = weibull_shape)
p7 = Pullout_embedded_elastoplastic_breakage_slipping(roots, interface, weibull_shape = weibull_shape)

p = p5
#print(p.behaviour_types)
print(p.limits[0])
print(p.limits[1])
# print(p.coefficients[0])
# print(p.coefficients[1])
# print(p.coefficients[2])
a, b, c, d = p.force(20 * units('mm'), jac = True)
print(a)
print(b)
print(c)
print(d)


#disp = 20.0 * units['mm']
#out = p.force(disp, jac = True)
#print(out)
#print(out[1])
#f,df,S,b = p.calculate(disp)
#print(f)
#print(S)
#print(b)

#p.plot(displacement_max = 300 * units['mm'])

[[0.0 0.028124999999999994 0.028124999999999994 0.278125] [0.0 0.16666666666666666 inf inf] [0.0 6.66666666666667e-06 inf inf]] meter
[[0.0 31.41592653589793 11.780972450961723 31.41592653589793] [0.0 188.49555921538757 282.7433388230814 188.49555921538757] [0.0 0.942477796076938 35.34291735288517 0.942477796076938]] newton
[9.934588265796103 65.29677711243184 0.942477796076938] newton
[248.36470664490255 1632.4194278107962 0.0] newton / meter
[1. 1. 1.]
[1 1 2]
