In [1]:
from pyrootmemo.fit.fit_xy_powerlaw import PowerlawFitWeibull
import numpy as np

In [9]:
# generate data
rng = np.random.default_rng()
x = np.linspace(1, 5, 50)
y = 10 * x**(-0.5) * rng.uniform(0.5, 1.5, len(x))
w = np.ones(len(x))

In [12]:
# Weibull
P = PowerlawFitWeibull(x, y)
print(P.colinear)
print(P.multiplier)
print(P.exponent)
print(P.shape)
print(P.random(np.array([2, 3, 4])))
print(P.ks_distance())
print(P.covariance())
print(P.covariance(method = 'bootstrap'))

False
9.18392396953024
-0.405372418953982
4.16621102383425
[7.97820809 6.5150027  7.11867273]
0.5590770050392733
[[ 0.69640873 -0.06057086  0.10941827]
 [-0.06057086  0.00641171 -0.00350668]
 [ 0.10941827 -0.00350668  0.21736127]]
[[ 0.81754909 -0.05991239  0.11204651]
 [-0.05991239  0.00537157 -0.00199658]
 [ 0.11204651 -0.00199658  0.17211449]]
