In [1]:
import numpy as np
from pyrootmemo.fit.fit_x import GumbelFit, WeibullFit, PowerFit
from pyrootmemo.fit.fit_x_binned import PowerFitBinned
from pyrootmemo.tools.helpers import units

In [2]:
# generate some data
rng = np.random.default_rng()
x = rng.normal(10, 1, 50)
xu = x * units('mm')

In [3]:
# Gumbel fit with units
Gu = GumbelFit(xu)
print(Gu.location)
print(Gu.scale)
print(Gu.random(10))
print(Gu.density())
print(Gu.density(cumulative = True))
print(Gu.covariance())
print(Gu.ks_distance())
print(Gu.loglikelihood(deriv = 0))
print(Gu.loglikelihood(deriv = 1))
print(Gu.loglikelihood(deriv = 2))

9.295743776653502 millimeter
0.7721201677349611 millimeter
[8.327771167307477 9.819887201531587 8.926039716282117 8.53125166526076 8.248693921067867 9.44251087594319 9.140141933486245 9.897259226189227 8.300362991168194 10.078734052715289] millimeter
[0.4250333370252923 0.21619890639310207 0.3943615384225893 0.3177089548087682 0.47141978352511205 0.08152168030572174 0.41533548505646095 0.4639862483490985 0.4047981039473163 0.41575808813876963 0.1945195540261711 0.31772658860658926 0.4619737902819272 0.30524104971697885 0.23574009956961686 0.4682043751616576 0.3867513532698825 0.058145553856707784 0.035766002305807135 0.10953608570852547 0.45603930593441755 0.07765463875925047 0.4651783329496258 0.38921495520467203 0.32584731254244603 0.3948742686494769 0.4408318846266727 0.18957629459166114 0.46607294861167975 0.43229179055082606 0.06606335131281846 0.09566454650893665 0.4296997025464343 0.2975215059624803 0.35996418491833904 0.45269154628183794 0.24574413308510593 0.456663710303308 0.

ValueError: setting an array element with a sequence.

In [ ]:
# Test Gumbel fit
G = GumbelFit(x)
print(G.location)
print(G.scale)
print(G.random(10))
print(G.covariance())
print(G.ks_distance())


9.46127464742141
1.0869399748960076
[12.13590265  9.11106392 12.6062325  10.60432633  9.47855073 12.81769555
  8.88569559  9.33223341  9.76856949  9.7864744 ]
[[0.02671776 0.00588801]
 [0.00588801 0.01122329]]
0.1552145798879569


In [ ]:
# test Weibull fit
W = WeibullFit(x)
print(W.shape)
print(W.scale)
print(W.random(10))
print(W.covariance())
print(W.ks_distance())
print(W.density())

10.651462561782719
10.421986161304925
[10.88353194  9.16896463 11.60789274 11.20994515  9.13788033 10.38853728
  9.07793529  9.10762558  9.4745378   9.6717535 ]
[[0.51224687 0.02609597]
 [0.02609597 0.00931475]]
0.10980021253155514
[0.37741646 0.34215499 0.37525042 0.36587609 0.01955111 0.3356485
 0.36442576 0.32557757 0.36035011 0.03066807 0.30242841 0.18905478
 0.26512999 0.31481331 0.36117066 0.21344203 0.34332217 0.08988169
 0.35682947 0.33874595 0.35859636 0.2006177  0.16635426 0.30236177
 0.1531847  0.35557712 0.3741302  0.37766423 0.16543209 0.33309184
 0.21338317 0.37764371 0.3720466  0.00571752 0.37761476 0.22130319
 0.22376195 0.37265189 0.04711414 0.09043668 0.28110545 0.37089871
 0.3614116  0.3771592  0.27807435 0.34729323 0.37720103 0.36679695
 0.31908522 0.34690426]


In [7]:
# Weibull with units
Wu = WeibullFit(xu)
print(Wu.shape)
print(Wu.scale)
print(Wu.random(10))
print(Wu.ks_distance())
print(Wu.density())
print(Wu.density(cumulative = True))
print(Wu.loglikelihood(deriv = 0))
print(Wu.loglikelihood(deriv = 1))
print(Wu.loglikelihood(deriv = 2))
print(Wu.covariance())




10.45115117719743
10.175541460695296 millimeter
[10.964150133882388 8.77399222145154 10.48407897941366 11.094995200986247 9.249595134749995 9.454281315375107 9.889635428891498 10.327262582564654 8.655504423009525 8.53262471419734] millimeter
0.1094762952223789 dimensionless
[0.35589954650737043 0.34141590461672666 0.22023045757747534 0.37941187688249706 0.2770539670725522 0.11873923560265112 0.3605656915672758 0.3265193591798104 0.22513342537706912 0.230688672350852 0.3220586137340866 0.3794127263505873 0.2638449476598629 0.18678157339592524 0.35482930308596344 0.2717215594651049 0.21684915853130196 0.0593707093412413 0.014868935786623247 0.18631439226948435 0.2578585378726249 0.10853921206919133 0.3250505264401387 0.37026324087002216 0.3796318523065344 0.36847926665677894 0.34664875269624706 0.15219831902364292 0.32389424709761033 0.24014947227885122 0.07890507284612794 0.15382656773738893 0.35340338833906787 0.3773306494343653 0.3769749519490162 0.2548761654138162 0.36038603921306395

DimensionalityError: Cannot convert from 'millimeter' ([length]) to 'dimensionless' (dimensionless)

In [ ]:
# generate some data - binned
xall = np.linspace(1, 10, 6)
xmin = xall[:-1]
xmax = xall[1:]
n = np.ones(len(xmin))
P = PowerFitBinned(xmin, xmax, n)
print(P.multiplier)
print(P.exponent)
print(P.lower)
print(P.upper)
print(P.random(10))
print(P.density(np.array([1, 2, 3])))

0.1270510672273536
-0.0720756234064388
1.1813500908995935
9.999999996523254
[5.99777435 9.09497706 7.01913458 8.6049799  7.82542437 8.31942132
 9.48538981 9.93050414 2.55163879 7.486368  ]
[0.         0.12085967 0.11737876]


In [ ]:
# test Power fit
P = PowerFit(x)
print(P.exponent)
print(P.lower)
print(P.upper)
print(P.random(10))
print(P.covariance())
print(P.ks_distance())
print(P.density())

0.9575566729246514
7.47967032855669
12.249327139058021
[11.64403972 10.571524   11.32473628 11.97127467  8.78734394 11.44191334
  9.17040223 10.57217253  9.39507752 10.40004743]
1.032748894097686
0.1852998040273739
[0.21664428 0.19392935 0.194218   0.20007107 0.18117823 0.16091434
 0.2014137  0.19585929 0.22190668 0.20999665 0.22266274 0.22662158
 0.20826733 0.17193885 0.23379505 0.2318689  0.1942803  0.22900244
 0.22442049 0.19413359 0.23179838 0.18065737 0.20183209 0.2258453
 0.24279134 0.21815128 0.19492125 0.2033778  0.21570619 0.2100013
 0.21210317 0.20058159 0.23953618 0.23823669 0.20948761 0.23107447
 0.22008223 0.23069492 0.19981879 0.23809131 0.2031062  0.22116566
 0.17639965 0.25806665 0.20081703 0.21662064 0.23050597 0.1867032
 0.23745956 0.23977847]
