In [1]:
from pyrootmemo.waldron import Waldron
from pyrootmemo.materials import MultipleRoots, Soil, Shearzone, Interface
from pyrootmemo.tools.helpers import units
import numpy as np

In [2]:
# generate some root data
from collections import namedtuple
Parameter = namedtuple("parameter", "value unit")
roots = MultipleRoots(
    species = "test_species",
    diameter = Parameter([1, 2, 1, 3, 4, 5, 6, 3], 'mm'),
    tensile_strength = Parameter([40, 30, 40, 20, 10, 5, 20, 10], 'MPa'),
    elastic_modulus = Parameter([100, 100, 100, 100, 100, 100, 20, 100], 'MPa'),
    length = Parameter([1, 1, 1, 1, 1, 1, 1, 1], 'm'),
    #azimuth_angle = Parameter([0, 0, 0, 0, 0, 0, 0, 0], 'degrees'),
    #elevation_angle = Parameter([-40, -30, -20, -10, 0, 10, 20, 30], 'degrees')
)
# generate some soil data
soil = Soil(
    "Sand",
    cohesion = Parameter(2, "kPa"),
    friction_angle = Parameter(30, "degrees")
)
# shearzone object
shearzone = Shearzone(
    area = Parameter(1, "m^2"),
    thickness = Parameter(10, "mm"),
    effective_stress = Parameter(20, "kPa")
)
# soil--root interface
interface = Interface(
    shear_strength = Parameter(10, "kPa")
)

In [3]:
# Create Waldron object
waldron = Waldron(shearzone, roots, soil, interface)

In [7]:
waldron.interface.shear_strength

<Quantity(10, 'kilopascal')>

In [4]:
print(roots.initial_orientation_vector())
print(roots.initial_orientation_vector(axis_angle = np.array([0.1, 0.1, 0.1])))

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[ 0.10448826 -0.09451324  0.99002498]
 [ 0.10448826 -0.09451324  0.99002498]
 [ 0.10448826 -0.09451324  0.99002498]
 [ 0.10448826 -0.09451324  0.99002498]
 [ 0.10448826 -0.09451324  0.99002498]
 [ 0.10448826 -0.09451324  0.99002498]
 [ 0.10448826 -0.09451324  0.99002498]
 [ 0.10448826 -0.09451324  0.99002498]]


In [5]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
np.stack((a, b), axis = 1)

array([[1, 1],
       [2, 2],
       [3, 3]])