In [1]:
import numpy as np
from pyrootmemo.fit.fit_x import GumbelFit, WeibullFit, PowerFit
from pyrootmemo.fit.fit_xy_binned import PowerFitBinned

In [7]:
# generate some data - binned
xall = np.linspace(1, 10, 6)
xmin = xall[:-1]
xmax = xall[1:]
n = np.ones(len(xmin))
P = PowerFitBinned(xmin, xmax, n)
print(P.multiplier)
print(P.exponent)
print(P.lower)
print(P.upper)
print(P.random(10))
print(P.density(np.array([1, 2, 3])))

0.1270510672273536
-0.0720756234064388
1.1813500908995935
9.999999996523254
[3.27404296 4.69975233 9.92508537 9.00778945 9.16154396 2.89931584
 8.75548481 9.17746872 5.90851443 3.84758057]
[0.         0.12085967 0.11737876]


In [2]:
# generate some data
rng = np.random.default_rng()
x = rng.normal(10, 1, 50)

In [3]:
# Test Gumbel fit
G = GumbelFit(x)
print(G.location)
print(G.scale)
print(G.random(10))
print(G.covariance())
print(G.ks_distance())




9.60490079879173
0.729191040976942
[ 9.26781411  9.78342602 10.13543759  9.93093396  9.29383239 10.36424169
 11.18269047  9.32441607 10.8478874   9.68405899]
[[0.0119009  0.00281268]
 [0.00281268 0.00624641]]
0.12314141765097819


In [4]:
# test Weibull fit
W = WeibullFit(x)
print(W.shape)
print(W.scale)
print(W.random(10))
print(W.covariance())
print(W.ks_distance())
print(W.density())

12.261494928195146
10.3940801891141
[10.36706676  9.75849025  8.89754906 10.26218941 10.32034756 10.10547582
 10.52767841 11.19602176 11.27021484  9.01672465]
[[0.68711456 0.02640411]
 [0.02640411 0.00703307]]
0.10619182983274889
[0.4309787  0.2538294  0.28907636 0.15884705 0.21285952 0.17044475
 0.22192478 0.37931504 0.43545132 0.42351217 0.11120774 0.14117961
 0.43231179 0.43250798 0.1744795  0.39367255 0.3814619  0.3321048
 0.43528237 0.40711823 0.19649388 0.3682331  0.37313293 0.21301932
 0.3376192  0.43520817 0.42468725 0.37932527 0.30511925 0.10622065
 0.43295804 0.41763077 0.26225739 0.22968303 0.34254824 0.40201974
 0.21133669 0.13430443 0.00538928 0.23103386 0.26695764 0.21045803
 0.42175733 0.42317781 0.42426799 0.41876484 0.42193989 0.39424806
 0.2103908  0.29113083]


In [5]:
# test Power fit
P = PowerFit(x)
print(P.exponent)
print(P.lower)
print(P.upper)
print(P.random(10))
print(P.covariance())
print(P.ks_distance())
print(P.density())

-2.66022763748583
8.452791902843838
12.210012225025544
[ 9.88323146 11.71154564  9.10731208  8.95174825 10.79283704  8.63873978
 11.17708302  9.3727667   9.65661129 11.14087023]
1.8077335145676543
0.13519147602890114
[0.26119365 0.33643572 0.32207929 0.38621066 0.20182611 0.37873906
 0.35083256 0.28793955 0.2522565  0.23998299 0.18878158 0.39879541
 0.24595621 0.25951545 0.37626416 0.28207072 0.28708627 0.2179098
 0.25099476 0.27604819 0.3637149  0.22424483 0.29036158 0.35517718
 0.30373418 0.25068862 0.2405893  0.2879355  0.21384949 0.42982662
 0.25894858 0.27063996 0.332881   0.34717509 0.30190344 0.27841626
 0.356017   0.19194082 0.1615893  0.34654954 0.20864952 0.20152967
 0.26820302 0.26729902 0.26657621 0.2378161  0.26808902 0.28182584
 0.35649187 0.21188562]
